name: docker-ci-pipiline
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'Contributions.md'
jobs:
  docker-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: image
        run: docker build -t rajkumarck/helloworld-demo-python:rt .
      - name: verify image
        run: docker images
      - name: create container
        run: docker run --name python-app -itd -p 8000:8080 rajkumarck/helloworld-demo-python:rt
      - name: sleep
        run: sleep 20
      - name: view container
        run: docker ps
      - name: check output
        run: curl -f http://localhost:8000
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
         username: ${{ vars.DOCKER_USERNAME }}
         password: ${{ secrets. DOCKER_Token }}
      - name: push image
        run: docker push rajkumarck/helloworld-demo-python:rt
      - name: Container Cleanup
        run: docker rm -f python-app
 
  k8scd-job:
    runs-on: ubuntu-latest
    needs: [docker-ci-job]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: start minikube
        uses: medyagh/setup-minikube@latest
      - name: test minikube
        run: kubectl get pods -A
      - name: apply.yaml files
        run: |
             kubectl apply -f k8s/.
             kubectl config set-context --current --namespace=python-app
             kubectl wait --for=condition=ready pod -l app=hello-world
      - name: get status
        run: |
          kubectl get ns
          kubectl get deploy,service -n python-app
      - name: Test service URLs
        run: |
          minikube service list
          minikube service simba --url
          echo -n "------------------opening the service------------------"
          curl -f $(minikube service simba --url)
